### ISSUE TITLE
No Unavailable limited rewards

### ISSUE THREAD

**Issue by Tankid** [timur-tabi/kickstarter-pledge-watch#9] opened 2016-01-23 08:01 UTC
Hello,
When I tried to use this script for some projects, it always shows this error in the title.
Here is one of the links used: 
https://www.kickstarter.com/projects/237916976/dreamscreen-smart-led-backlighting-for-any-hdmi-tv
Thank you

**Comment by timur-tabi** [comment] 2016-01-23 14:12
Looks like they changed the HTML again.  It shouldn't be too hard to fix, but I won't be able to get to it for a while.

**Comment by Tankid** [comment] 2016-01-23 15:36
ah, ok, waiting for you then.
Thanks in advance

**Comment by timur-tabi** [comment] 2016-01-30 18:16
This should be fixed now.  Please test it.

**Comment by timur-tabi** [comment] 2016-01-30 20:04
This should be fixed now.  Please try it.

**Comment by Tankid** [comment] 2016-02-02 14:50
It's working now, thanks.
However, I face a problem after running the script for some time, usually more than 1 hour, I get this error and nothing happens after:
" URL Error <erlopen error [Errno 11001] getaddrinfo faild>"
Retrying in one minute

And it gets stuck to this.

**Comment by timur-tabi** [comment] 2016-02-02 14:58
Can you give me the full error message.  There should be something after "URL Error".

**Comment by Tankid** [comment] 2016-02-02 15:08
I wrote the error, but it looks like it was hidden, edited the comment

**Comment by timur-tabi** [comment] 2016-02-07 17:21
That sounds like a generic connection problem with the kickstarter.com web site.  I've never seen it before, but I will try to reproduce it when I have time.  I don't personally use the script any more, so it might be few weeks before I can look at it.

However, I don't know how to fix this.  It appears that the "f = urllib2.urlopen(url)" call on line 59 is generating a URLError exception, and that's not something I can debug.  The script tries to download a page, and kickstarter.com is not responding properly.

The only thing I can suggest is that you slow the script down.  Try changing the "time.sleep(60)" on line 194 to "time.sleep(300)".  That will make it check every 5 minutes instead of every one minute.  Let me know if that helps.

**Comment by Tankid** [comment] 2016-02-07 17:29
Sorry for that, the script is 100% working, and when that error shows, I think because of the hotel internet is too bad. Thank you for the fix, and good luck.

**Comment by timur-tabi** [comment] 2016-02-07 17:32
Well, I can't fix bad Internet connections.  I'm going to close this issue for now.  If you have anything more substantial, then reopen it.

**Closed by timur-tabi** 2016-02-07 17:32 UTC
